// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nibbler.Usuario.Infra.Data;

#nullable disable

namespace Nibbler.Usuario.Infra.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    partial class UsuarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nibbler.Usuario.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataDeCadastro");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CaminhoFoto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Nibbler.Usuario.Domain.Usuario", b =>
                {
                    b.OwnsOne("Nibbler.Usuario.Domain.Login", "Login", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Hash")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LoginHash");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.OwnsOne("Nibbler.Core.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("LoginUsuarioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Endereco")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("Email");

                                    b2.HasKey("LoginUsuarioId");

                                    b2.ToTable("Usuarios");

                                    b2.WithOwner()
                                        .HasForeignKey("LoginUsuarioId");
                                });

                            b1.OwnsOne("Nibbler.Core.ValueObjects.Senha", "Senha", b2 =>
                                {
                                    b2.Property<Guid>("LoginUsuarioId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)")
                                        .HasColumnName("Senha");

                                    b2.HasKey("LoginUsuarioId");

                                    b2.ToTable("Usuarios");

                                    b2.WithOwner()
                                        .HasForeignKey("LoginUsuarioId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("Senha")
                                .IsRequired();
                        });

                    b.Navigation("Login")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
